- name: "Install CTF Gameserver VPN Status component"
  ansible.builtin.apt:
    state: present
    deb: "{{ ctf_gameserver_downloadpath }}/{{ item }}"
  with_items: "{{ ctf_gameserver_vpnstatus_packages }}"

- name: "Add config for CTF Gameserver VPN Status"
  ansible.builtin.template:
    src: vpnstatus.env.j2
    dest: /etc/ctf-gameserver/vpnstatus.env
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart CTF Gameserver VPN Status

- name: "Install sudo"
  ansible.builtin.apt:
    name: sudo
    state: present

- name: "Add sudoers config for CTF Gameserver VPN Status"
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/ctf-vpnstatus
    owner: root
    group: root
    mode: "0600"

- name: "Enable CTF Gameserver VPN Status"
  ansible.builtin.service:
    name: ctf-vpnstatus
    enabled: true
