namespace: fausecteam
name: ctf_gameserver_ansible
description: Roles to simplify setting up the different components of FAUST's CTF Gameserver
version: 2.0.0

authors:
  - FAUST -- FAU Security Team
  - Felix Dreissig <f30@f30.me>

license:
  - ISC

readme: README.md
repository: https://github.com/fausecteam/ctf-gameserver-ansible
issues: https://github.com/fausecteam/ctf-gameserver-ansible/issues
homepage: https://ctf-gameserver.org/

tags:
  - ctf
  - security
  - clustering
  - installer
  - debian
  - python
  - database
  - web

dependencies:
  community.postgresql: ">=2.0,<4.0"
