- name: "Install CTF Gameserver controller component"
  ansible.builtin.apt:
    state: present
    deb: "{{ ctf_gameserver_downloadpath }}/{{ item }}"
  with_items: "{{ ctf_gameserver_controller_packages }}"

- name: "Add config for CTF Gameserver controller"
  ansible.builtin.template:
    src: controller.env.j2
    dest: /etc/ctf-gameserver/controller.env
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart CTF Gameserver controller

- name: "Enable CTF Gameserver controller"
  ansible.builtin.service:
    name: ctf-controller
    enabled: true
