- name: "Install CTF Gameserver submission component"
  apt:
    state: present
    deb: "{{ ctf_gameserver_downloadpath }}/{{ item }}"
  with_items: "{{ ctf_gameserver_submission_packages }}"

- name: "Add config for CTF Gameserver submission component"
  template:
    src: submission.env.j2
    dest: /etc/ctf-gameserver/submission.env
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart CTF Gameserver submission

- name: "Start CTF Gameserver submission component"
  service:
    name: ctf-submission@{{ item }}
    state: started
    enabled: true
  with_items: "{{ ctf_gameserver_submission_listen_ports }}"
