- name: "Install CTF Gameserver checker component"
  apt:
    state: present
    deb: "{{ ctf_gameserver_downloadpath }}/{{ item }}"
  with_items: "{{ ctf_gameserver_checker_packages }}"

- name: "Add config for CTF Gameserver checkermaster"
  template:
    src: checkermaster.env.j2
    dest: /etc/ctf-gameserver/checkermaster.env
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart CTF Gameserver checkers
