- name: "Install Django"
  ansible.builtin.apt:
    state: present
    name: python3-django

- name: "Install CTF Gameserver web component"
  ansible.builtin.apt:
    state: present
    deb: "{{ ctf_gameserver_downloadpath }}/{{ item }}"
  with_items: "{{ ctf_gameserver_web_packages }}"

- name: "Add config for CTF Gameserver web component"
  ansible.builtin.template:
    src: prod_settings.py.j2
    dest: /etc/ctf-gameserver/web/prod_settings.py
    owner: root
    group: "{{ ctf_gameserver_web_group }}"
    mode: "0640"

- name: "Create CTF Gameserver web uploads directory"
  ansible.builtin.file:
    path: "{{ ctf_gameserver_web_media_root }}"
    state: directory
    owner: root
    group: "{{ ctf_gameserver_web_group }}"
    mode: "0770"

- name: "Create CTF Gameserver team downloads directory"
  ansible.builtin.file:
    path: "{{ ctf_gameserver_web_team_downloads_root }}"
    state: directory
    owner: root
    group: "{{ ctf_gameserver_web_group }}"
    mode: "0750"

- name: "Initialize Django auth in CTF Gameserver database"
  ansible.builtin.command: django-admin migrate auth
  environment:
    PYTHONPATH: /etc/ctf-gameserver/web
    DJANGO_SETTINGS_MODULE: prod_settings
  register: migrate_auth_result
  changed_when: "'No migrations to apply.' not in migrate_auth_result.stdout"
  run_once: true

- name: "Initialize CTF Gameserver database"
  ansible.builtin.command: django-admin migrate
  environment:
    PYTHONPATH: /etc/ctf-gameserver/web
    DJANGO_SETTINGS_MODULE: prod_settings
  register: migrate_result
  changed_when: "'No migrations to apply.' not in migrate_result.stdout"
  run_once: true

- name: "Install pexpect (for Ansible)"
  ansible.builtin.apt:
    name: python3-pexpect
    state: present

- name: "Create admin account for CTF Gameserver web component"
  ansible.builtin.expect:
    command: django-admin createsuperuser --username {{ ctf_gameserver_web_admin_user }} --email {{ ctf_gameserver_web_admin_email }}
    responses:
      Password: "{{ ctf_gameserver_web_admin_pass }}"
    timeout: 5
    creates: /root/.ansible_ctf_gameserver_web_admin_createstamp
  environment:
    PYTHONPATH: /etc/ctf-gameserver/web
    DJANGO_SETTINGS_MODULE: prod_settings
  register: ctf_gameserver_web_create_admin
  run_once: true

- name: "Add admin account create stamp"
  ansible.builtin.file:
    path: /root/.ansible_ctf_gameserver_web_admin_createstamp
    state: touch
  when: ctf_gameserver_web_create_admin.changed
