- name: "Install PostgreSQL"
  apt:
    name: postgresql
    state: present

- name: "Install psycopg2 (for Ansible)"
  apt:
    name: python3-psycopg2
    state: present

- name: "Create database for CTF Gameserver"
  postgresql_db:
    name: "{{ ctf_gameserver_db_name }}"
    state: present
    login_unix_socket: /run/postgresql
  run_once: true
  become: true
  become_user: postgres

- name: "Revoke privileges for PUBLIC from the database"
  postgresql_privs:
    database: "{{ ctf_gameserver_db_name }}"
    type: database
    roles: PUBLIC
    privs: ALL
    state: absent
    login_unix_socket: /run/postgresql
  run_once: true
  become: true
  become_user: postgres

# Use the default "public" schema and make it not-so-public, this is a common practice according to
# https://stackoverflow.com/a/25586847
- name: "Revoke privileges for PUBLIC from the database schemas"
  postgresql_privs:
    database: "{{ ctf_gameserver_db_name }}"
    type: schema
    objs: public
    roles: PUBLIC
    privs: ALL
    state: absent
    login_unix_socket: /run/postgresql
  run_once: true
  become: true
  become_user: postgres

- name: "Create database users for CTF Gameserver components"
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    encrypted: true
    state: present
    login_unix_socket: /run/postgresql
  with_items:
    - user: "{{ ctf_gameserver_db_user_controller }}"
      pass: "{{ ctf_gameserver_db_pass_controller }}"
    - user: "{{ ctf_gameserver_db_user_web }}"
      pass: "{{ ctf_gameserver_db_pass_web }}"
    - user: "{{ ctf_gameserver_db_user_checker }}"
      pass: "{{ ctf_gameserver_db_pass_checker }}"
    - user: "{{ ctf_gameserver_db_user_submission }}"
      pass: "{{ ctf_gameserver_db_pass_submission }}"
  run_once: true
  become: true
  become_user: postgres
  # Hide passwords from the command line output
  no_log: true

- name: "Allow database users to connect to the Gameserver database"
  postgresql_privs:
    database: "{{ ctf_gameserver_db_name }}"
    type: database
    roles: "{{ item }}"
    privs: CONNECT
    state: present
    login_unix_socket: /run/postgresql
  with_items:
    - "{{ ctf_gameserver_db_user_controller }}"
    - "{{ ctf_gameserver_db_user_web }}"
    - "{{ ctf_gameserver_db_user_checker }}"
    - "{{ ctf_gameserver_db_user_submission }}"
  run_once: true
  become: true
  become_user: postgres

- name: "Allow database users to use the Gameserver database schema"
  postgresql_privs:
    database: "{{ ctf_gameserver_db_name }}"
    type: schema
    objs: public
    roles: "{{ item }}"
    privs: USAGE
    state: present
    login_unix_socket: /run/postgresql
  with_items:
    - "{{ ctf_gameserver_db_user_controller }}"
    - "{{ ctf_gameserver_db_user_web }}"
    - "{{ ctf_gameserver_db_user_checker }}"
    - "{{ ctf_gameserver_db_user_submission }}"
  run_once: true
  become: true
  become_user: postgres

- name: "(Temporarily) allow web component database user to create objects in the schema"
  postgresql_privs:
    database: "{{ ctf_gameserver_db_name }}"
    type: schema
    objs: public
    roles: "{{ ctf_gameserver_db_user_web }}"
    privs: CREATE
    state: present
    login_unix_socket: /run/postgresql
  run_once: true
  become: true
  become_user: postgres
