- name: "Install CTF Gameserver checker component"
  ansible.builtin.apt:
    state: present
    deb: "{{ ctf_gameserver_downloadpath }}/{{ item }}"
  with_items: "{{ ctf_gameserver_checker_packages }}"

- name: "Install sudo"
  ansible.builtin.apt:
    name: sudo
    state: present

- name: "Add sudoers config for CTF Gameserver checker component"
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/ctf-checker
    owner: root
    group: root
    mode: 0600

- name: "Add config for CTF Gameserver checkermaster"
  ansible.builtin.template:
    src: checkermaster.env.j2
    dest: /etc/ctf-gameserver/checkermaster.env
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart CTF Gameserver checkers
